name: Keep Alive and Daily Reset

on:
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos, faz o "keep alive"
    - cron: '0 3 * * *'     # Todo dia à meia-noite UTC, faz o reset
  workflow_dispatch:

jobs:
  keep-alive:
    if: github.event.schedule == '*/10 * * * *'
    runs-on: ubuntu-latest

    steps:
      - name: Keep the app alive
        run: |
          curl https://life-rpg-backend.onrender.com/

  daily-reset:
    if: github.event.schedule == '0 0 * * *'
    runs-on: ubuntu-latest

    steps:
      - name: Reset missions at midnight
        run: |
          curl -X POST https://life-rpg-backend.onrender.com/reset_missions
