name: Keep Alive and Daily Reset

on:
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos (keep-alive)
    - cron: '0 3 * * *'    # À meia-noite UTC (daily reset)
  workflow_dispatch:       # Permite rodar manualmente

jobs:
  keep-alive-and-reset:
    runs-on: ubuntu-latest

    steps:
      - name: Keep the app alive
        run: |
          curl https://life-rpg-backend.onrender.com/

      - name: Reset missions at midnight
        run: |
          curl -X POST https://life-rpg-backend.onrender.com/daily-update
